export const REPORTE_FETCH_REPORTE_BEGIN = 'REPORTE_FETCH_REPORTE_BEGIN';
export const REPORTE_FETCH_REPORTE_SUCCESS = 'REPORTE_FETCH_REPORTE_SUCCESS';
export const REPORTE_FETCH_REPORTE_FAILURE = 'REPORTE_FETCH_REPORTE_FAILURE';
export const REPORTE_FETCH_REPORTE_DISMISS_ERROR = 'REPORTE_FETCH_REPORTE_DISMISS_ERROR';
export const REPORTE_LIMPIAR_DATA = 'REPORTE_LIMPIAR_DATA';
