export const PERSONAS_FETCH_PERSONAS_BEGIN = 'PERSONAS_FETCH_PERSONAS_BEGIN';
export const PERSONAS_FETCH_PERSONAS_SUCCESS = 'PERSONAS_FETCH_PERSONAS_SUCCESS';
export const PERSONAS_FETCH_PERSONAS_FAILURE = 'PERSONAS_FETCH_PERSONAS_FAILURE';
export const PERSONAS_FETCH_PERSONAS_DISMISS_ERROR = 'PERSONAS_FETCH_PERSONAS_DISMISS_ERROR';
