export const REUNIONES_FETCH_REUNIONES_BEGIN = 'REUNIONES_FETCH_REUNIONES_BEGIN';
export const REUNIONES_FETCH_REUNIONES_SUCCESS = 'REUNIONES_FETCH_REUNIONES_SUCCESS';
export const REUNIONES_FETCH_REUNIONES_FAILURE = 'REUNIONES_FETCH_REUNIONES_FAILURE';
export const REUNIONES_FETCH_REUNIONES_DISMISS_ERROR = 'REUNIONES_FETCH_REUNIONES_DISMISS_ERROR';
